# Generated by Django 4.0.4 on 2022-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_post_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
